version: '2'
services:
  nginx:
    image: lksoia89/nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
  site:
    image: lksoia89/site:0.0.4
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443