version: "2"
services:
  site:
    volumes:
      - ./env/dev/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./env/dev/conf/mattkirwan.test.conf:/etc/nginx/conf.d/mattkirwan.test.conf:ro
      - ./public:/var/www/mattkirwan.test
      - ./env/dev/ssl:/etc/nginx/ssl
    environment:
      DEBUG: 'true'